# Generated by Django 3.1.3 on 2020-11-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='nome',
            field=models.CharField(default='Lista sem nome', max_length=50),
        ),
        migrations.AddField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='compras.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
    ]
