# Generated by Django 3.1.3 on 2020-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='listas',
            field=models.ManyToManyField(null=True, related_name='produtos', to='compras.Lista'),
        ),
    ]
