# Generated by Django 3.1.3 on 2020-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20201121_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='listas',
            field=models.ManyToManyField(to='compras.Lista'),
        ),
    ]
