# Generated by Django 3.1.3 on 2020-11-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_auto_20201121_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=6)),
                ('validade', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=7)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.CharField(max_length=50)),
                ('produtos', models.CharField(max_length=10000)),
                ('supermercado', models.CharField(max_length=100)),
                ('cartao', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='listas',
        ),
        migrations.AlterField(
            model_name='lista',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='SupermercadoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supermercados', to='compras.produto')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='compras.supermercado')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='compras.lista')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='compras.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.cartao')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.endereco')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.lista')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.supermercado')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
