# Generated by Django 3.1.3 on 2020-11-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20201123_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='valor',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='produtos',
        ),
        migrations.CreateModel(
            name='ProdutoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='compras.historico')),
            ],
        ),
    ]
