# Generated by Django 3.1.3 on 2020-11-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_auto_20201126_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='compras.usuario'),
            preserve_default=False,
        ),
    ]
