# Generated by Django 3.1.3 on 2020-12-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_auto_20201202_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='categoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
