# Generated by Django 3.1.3 on 2020-12-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_lista_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
