# Generated by Django 3.1.3 on 2020-12-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_auto_20201209_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAcompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='compras.acompanhamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='compras.produto')),
            ],
        ),
    ]
