# Generated by Django 3.1.3 on 2020-12-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_produtoacompanhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='acompanhamento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='acompanhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='compras.acompanhamento'),
        ),
    ]
