# Generated by Django 3.1.3 on 2020-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_produto_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercado',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='img_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
