# Generated by Django 3.1.3 on 2020-12-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_auto_20201213_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(choices=[('Retirada', 'Retirada'), ('Entrega', 'Entrega')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.endereco'),
        ),
    ]
