# Generated by Django 3.2.5 on 2021-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_produto_codigo_de_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
